### ISSUE TITLE
using in my app

### ISSUE THREAD

**Issue by FragsterAt** [goodmind/telegram-mtproto#1]
i have some questions:
1. file in this line:
> require('./api-schema-57.json')
i must download from https://core.telegram.org/schema/json ?
2. how to provide my app id?
3. how to get and reuse authkey to sign in without sms code?

**Comment by FragsterAt** [comment]
how can i generate object for Telegram.addPublicKey?

**Comment by goodmind** [comment]
See my app:

Public keys here:
https://github.com/goodmind/treact/blob/master/src/app/helpers/Telegram/publickeys.ts

Schema here:
https://github.com/goodmind/treact/blob/master/src/app/helpers/Telegram/api-tlschema-57.json

Currently telegram-mtproto is WIP and maintained by @zerobias. He is going to replace it with rewrited webogram, because it doesn't supports multiple datacenter connections (which is important for [treact](https://github.com/goodmind/treact))

**Comment by FragsterAt** [comment]
I use npm packet, so I don't know, which version is installed.

It works with your api-shema file (there was strange errors with shema from telegram.org)! Thanks! Now I'try to add contacts with ciryllic names, which is broken in telegram.link (see https://github.com/enricostara/telegram.link/pull/34 )

**Comment by goodmind** [comment]
@FragsterAt npm have zerobias's version, so you are fine

**Comment by FragsterAt** [comment]
@zerobias can you look at this one? https://github.com/zerobias/telegram-mtproto/issues/6
